collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5071685
  brandStrength: 0.8513571871444583
  lightness: 0.2437276
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  rhythmicContrast: 0.6630824
typography_spectrum: 0.07308984524570405
layout_spectrum: 0.5143369
name: alex&uncle brad
