collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.07308984524570405
color:
  saturation: 0.6958594834432006
  brandStrength: 0.8513571871444583
  rhythmicContrast: 0.344623239710927
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.8403616917785257
layout_spectrum: 0.5143369
name: alex&uncle brad
